'use client';

import { motion } from 'framer-motion';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Link from 'next/link';

export default function PrivacyPolicy() {
  const sections = [
    {
      title: 'Definitions',
      content: [
        { subtitle: 'Service', text: 'Service is the https://inaipi.ai/ website operated by Inaipi Private Limited' },
        { subtitle: 'Personal Data', text: 'Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).' },
        { subtitle: 'Usage Data', text: 'Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
        { subtitle: 'Cookies', text: 'Cookies are small files stored on your device (computer or mobile device).' },
        { subtitle: 'Data Controller', text: 'Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.' },
        { subtitle: 'Data Processors (or Service Providers)', text: 'Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.' },
        { subtitle: 'Data Subject (or User)', text: 'Data Subject is any living individual who is using our Service and is the subject of Personal Data.' }
      ]
    },
    {
      title: 'Information Collection & Use',
      content: [
        { text: 'We collect several different types of information for various purposes to provide and improve our Service to you.' }
      ]
    },
    {
      title: 'Type of data collected',
      content: [
        { subtitle: 'Personal Data', text: 'While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:' },
        { list: ['Email address', 'First name and last name', 'Phone number', 'Address, State, Province, ZIP/Postal code, City', 'Cookies and Usage Data'] },
        { text: 'We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.' }
      ]
    },
    {
      title: 'Usage Data',
      content: [
        { text: 'We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.' }
      ]
    },
    {
      title: 'Tracking & Cookies Data',
      content: [
        { text: 'We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.' },
        { text: 'Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.' },
        { text: 'You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.' },
        { subtitle: 'Examples of Cookies we use:', list: ['Session Cookies. We use Session Cookies to operate our Service.', 'Preference Cookies. We use Preference Cookies to remember your preferences and various settings.', 'Security Cookies. We use Security Cookies for security purposes.'] }
      ]
    },
    {
      title: 'Use of Data',
      content: [
        { text: 'Inaipi Private Limited uses the collected data for various purposes:' },
        { list: ['To provide and maintain our Service', 'To notify you about changes to our Service', 'To allow you to participate in interactive features of our Service when you choose to do so', 'To provide customer support', 'To gather analysis or valuable information so that we can improve our Service', 'To monitor the usage of our Service', 'To detect, prevent and address technical issues', 'To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information'] }
      ]
    },
    {
      title: 'Legal Basis for Processing Personal Data under General Data Protection Regulation (GDPR)',
      content: [
        { text: 'If you are from the European Economic Area (EEA), Inaipi Private Limited legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.' },
        { text: 'Inaipi Private Limited may process your Personal Data because:' },
        { list: ['We need to perform a contract with you', 'You have given us permission to do so', 'The processing is in our legitimate interests and it is not overridden by your rights', 'For payment processing purposes', 'To comply with the law'] }
      ]
    },
    {
      title: 'Retention of Data',
      content: [
        { text: 'Inaipi Private Limited will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.' },
        { text: 'Inaipi Private Limited will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.' }
      ]
    },
    {
      title: 'Transfer of Data',
      content: [
        { text: 'Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.' },
        { text: 'If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.' },
        { text: 'Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.' },
        { text: 'Inaipi Private Limited will take all the steps reasonably necessary to ensure that your data is securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.' }
      ]
    },
    {
      title: 'Disclosure of Data',
      content: [
        { subtitle: 'Legal Requirements', text: 'Inaipi Private Limited may disclose your Personal Data in the good faith belief that such action is necessary to:' },
        { list: ['To comply with a legal obligation', 'To protect and defend the rights or property of Inaipi Private Limited', 'To prevent or investigate possible wrongdoing in connection with the Service', 'To protect the personal safety of users of the Service or the public', 'To protect against legal liability'] }
      ]
    },
    {
      title: 'Security of Data',
      content: [
        { text: 'The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.' }
      ]
    },
    {
      title: 'Contact Us',
      content: [
        { text: 'If you have any questions about this Privacy Policy, please contact us- aisupport@inaipi.ai' }
      ]
    }
  ];

  return (
    <main className="min-h-screen bg-white font-figtree overflow-x-hidden">
      <Navbar />

      {/* Hero */}
      <section className="pt-32 lg:pt-36 pb-14 relative overflow-hidden" style={{ background: '#f8faff' }}>
        <div className="absolute inset-0 z-0 pointer-events-none overflow-hidden">
          <div className="absolute inset-0" style={{ background: 'radial-gradient(ellipse 100% 60% at 50% 0%, rgba(37,99,235,0.18) 0%, transparent 70%)' }} />
          <div className="absolute inset-0" style={{ backgroundImage: 'radial-gradient(circle, rgba(37,99,235,0.18) 1.2px, transparent 1.2px)', backgroundSize: '32px 32px', maskImage: 'radial-gradient(ellipse 100% 85% at 50% 10%, black 30%, transparent 100%)' }} />
          <div className="absolute inset-0" style={{ backgroundImage: 'repeating-linear-gradient(0deg, rgba(37,99,235,0.04) 0px, rgba(37,99,235,0.04) 1px, transparent 1px, transparent 32px), repeating-linear-gradient(90deg, rgba(37,99,235,0.04) 0px, rgba(37,99,235,0.04) 1px, transparent 1px, transparent 32px)', maskImage: 'radial-gradient(ellipse 100% 70% at 50% 0%, black 0%, transparent 100%)' }} />
          <motion.div className="absolute rounded-full" style={{ width: 1100, height: 1100, top: '-35%', left: '50%', x: '-50%', background: 'radial-gradient(circle, rgba(37,99,235,0.32) 0%, rgba(0,111,255,0.18) 40%, transparent 70%)', filter: 'blur(90px)' }} animate={{ scale: [1, 1.12, 1], opacity: [0.8, 1, 0.8] }} transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }} />
          <motion.div className="absolute rounded-full" style={{ width: 800, height: 800, top: '5%', left: '-20%', background: 'radial-gradient(circle, rgba(0,111,255,0.26) 0%, transparent 65%)', filter: 'blur(80px)' }} animate={{ x: [0, 60, 0], y: [0, 40, 0] }} transition={{ duration: 14, repeat: Infinity, ease: 'easeInOut' }} />
          <motion.div className="absolute rounded-full" style={{ width: 700, height: 700, top: '0%', right: '-15%', background: 'radial-gradient(circle, rgba(0,231,255,0.22) 0%, transparent 65%)', filter: 'blur(80px)' }} animate={{ x: [0, -60, 0], y: [0, 50, 0] }} transition={{ duration: 16, repeat: Infinity, ease: 'easeInOut', delay: 2 }} />
          <motion.div className="absolute w-3 h-3 rounded-full bg-blue-500/40" style={{ top: '18%', left: '12%', filter: 'blur(2px)' }} animate={{ y: [0, -18, 0], opacity: [0.4, 0.9, 0.4] }} transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }} />
          <motion.div className="absolute w-2 h-2 rounded-full bg-[#006fff]/50" style={{ top: '28%', right: '14%', filter: 'blur(1px)' }} animate={{ y: [0, -14, 0], opacity: [0.5, 1, 0.5] }} transition={{ duration: 4.5, repeat: Infinity, ease: 'easeInOut', delay: 1 }} />
          <motion.div className="absolute w-4 h-4 rounded-full bg-[#00e7ff]/30" style={{ top: '10%', left: '38%', filter: 'blur(3px)' }} animate={{ y: [0, -22, 0], opacity: [0.3, 0.8, 0.3] }} transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }} />
          <motion.div className="absolute w-2 h-2 rounded-full bg-blue-400/50" style={{ top: '35%', left: '22%', filter: 'blur(1px)' }} animate={{ y: [0, -12, 0], opacity: [0.4, 0.9, 0.4] }} transition={{ duration: 3.8, repeat: Infinity, ease: 'easeInOut', delay: 1.5 }} />
          <motion.div className="absolute w-3 h-3 rounded-full bg-[#006fff]/35" style={{ top: '20%', right: '28%', filter: 'blur(2px)' }} animate={{ y: [0, -16, 0], opacity: [0.35, 0.8, 0.35] }} transition={{ duration: 5.5, repeat: Infinity, ease: 'easeInOut', delay: 0.8 }} />
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px]" style={{ background: 'conic-gradient(from 255deg at 50% 0%, transparent 15%, rgba(37,99,235,0.18) 30%, rgba(0,111,255,0.22) 50%, rgba(37,99,235,0.18) 70%, transparent 85%)', filter: 'blur(18px)' }} />
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-px h-[35%]" style={{ background: 'linear-gradient(to bottom, rgba(0,111,255,0.6) 0%, transparent 100%)' }} />
          <div className="absolute top-0 left-[42%] w-px h-[25%]" style={{ background: 'linear-gradient(to bottom, rgba(37,99,235,0.35) 0%, transparent 100%)', transform: 'rotate(6deg)', transformOrigin: 'top' }} />
          <div className="absolute top-0 left-[58%] w-px h-[25%]" style={{ background: 'linear-gradient(to bottom, rgba(37,99,235,0.35) 0%, transparent 100%)', transform: 'rotate(-6deg)', transformOrigin: 'top' }} />
          <div className="absolute bottom-0 left-0 right-0 h-40" style={{ background: 'linear-gradient(to top, white 0%, transparent 100%)' }} />
        </div>

        <div className="container mx-auto px-6 max-w-7xl relative z-10">
          {/* Breadcrumb */}
          <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }} className="flex items-center gap-2 mb-10">
            <Link href="/" className="text-[11px] font-bold text-[#0f172a] hover:text-[#1447d4] transition-colors">Home</Link>
            <svg className="w-3 h-3 text-slate-300" fill="none" stroke="currentColor" strokeWidth={2.5} viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" /></svg>
            <span className="text-[11px] font-bold text-[#1447d4]">Privacy Policy</span>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="mb-16">
            <h1 className="text-4xl sm:text-5xl lg:text-[4rem] font-bold font-figtree tracking-[-0.03em] text-[#0f172a] leading-[1.15] mb-6">Privacy <span className="inline-block text-[#1447d4] pb-2">Policy</span></h1>
            <p className="text-[16px] text-slate-500 font-medium">Effective date: July 01, 2023</p>
          </motion.div>

        </div>
      </section>

      {/* Content */}
      <section className="py-14 lg:py-16 bg-white">
        <div className="container mx-auto px-6 max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="space-y-14"
          >
            <p className="text-[16px] text-slate-600 leading-relaxed">
              Inaipi Private Limited ("us", "we", or "our") operates the https://inaipi.ai/ website (hereinafter referred to as the "Service"). This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data. We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://inaipi.ai/
            </p>

            {sections.map((section, idx) => (
              <div key={idx} className="space-y-5 pb-10 border-b border-slate-100 last:border-0 last:pb-0">
                <h2 className="text-2xl sm:text-3xl font-bold font-figtree tracking-[-0.025em] text-[#0f172a] leading-[1.15]">{section.title}</h2>
                <div className="space-y-4">
                  {section.content.map((item, pIdx) => (
                    <div key={pIdx} className="space-y-2">
                      {item.subtitle && (
                        <h3 className="text-[18px] font-bold font-figtree text-[#0f172a]">{item.subtitle}</h3>
                      )}
                      {item.text && (
                        <p className="text-[16px] text-slate-600 leading-relaxed">
                          {item.text}
                        </p>
                      )}
                      {item.list && (
                        <ul className="space-y-2 text-[16px] text-slate-600 leading-relaxed pl-1">
                          {item.list.map((listItem, liIdx) => (
                            <li key={liIdx} className="flex items-start gap-3">
                              <span className="w-1.5 h-1.5 rounded-full bg-blue-400 mt-2.5 shrink-0" />
                              {listItem}
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
